# Generated by Django 4.2.1 on 2023-06-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'Reopened'), ('3', 'Resolved'), ('4', 'Closed'), ('5', 'Duplicate')], max_length=1)),
                ('priority', models.CharField(choices=[('1', '1. Critical'), ('2', '2. High'), ('3', '3. Normal'), ('4', '4. Low'), ('5', '5. Very Low')], max_length=1)),
                ('media', models.ManyToManyField(related_name='tickets', to='ticket.media')),
            ],
        ),
    ]
