# Generated by Django 4.2.1 on 2023-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_media", "0001_initial"),
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="image",
            field=models.ManyToManyField(
                null=True, related_name="ticket_images", to="upload_media.uploadmedia"
            ),
        ),
    ]
