# Generated by Django 4.2.1 on 2023-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('1', 'Critical'), ('2', 'High'), ('3', 'Normal'), ('4', 'Low'), ('5', 'Very Low')], max_length=1),
        ),
    ]
