# Generated by Django 4.2.1 on 2023-06-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_ticket_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
