# Generated by Django 4.2.1 on 2023-06-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='media',
        ),
    ]
