# Generated by Django 4.2.1 on 2023-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_remove_ticket_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='media',
            field=models.ManyToManyField(null=True, related_name='tickets', to='ticket.media'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('verylow', 'Very Low')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Reopened'), ('3', 'Resolved'), ('4', 'Closed'), ('5', 'Duplicate')], default='1', max_length=1),
        ),
    ]
