# Generated by Django 4.2.1 on 2023-06-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticket_media_ticket_priority_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='media',
        ),
    ]
